---
title: "QualityTrimming"
author: "Morrow Zhang"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center",
                      #make sure to create the folder 
                      fig.path = "../figures/01_QualityTrimming")


```

```{r}
set.seed(238428)
```

```{r}
pacman::p_load(tidyverse, dada2, patchwork, 
               Biostrings, ShortRead,
               install = FALSE)
```

```{r}
raw_fastqs_path <- "data/00_raw_gzipped_fastqs"
list.files(raw_fastqs_path) %>% head()
forward_reads <- list.files(raw_fastqs_path, pattern = "_1.fastq.gz", full.names = TRUE)
head(forward_reads)
reverse_reads <- list.files(raw_fastqs_path, pattern = "_2.fastq.gz", full.names = TRUE)
head(reverse_reads)

length(forward_reads)
length(reverse_reads)
```
```{r Assess Quality}

forward_preQC_plot <- 
  plotQualityProfile(forward_reads, aggregate = TRUE) + 
  labs(title = "Forward Pre-QC")

reverse_preQC_plot <- 
  plotQualityProfile(reverse_reads, aggregate = TRUE) + 
  labs(title = "Reverse Pre-QC")

preQC_aggregate_plot <- 
  forward_preQC_plot + reverse_preQC_plot

preQC_aggregate_plot
```
```{r Primer Search}

raw_fastqs <- readFastq(dirPath = raw_fastqs_path, pattern = ".fastq.gz")
all_seqs <- sread(raw_fastqs)

f_primer <- c("CCTACGGGNGGCWGCAG")
r_primer <- c("GACTACHVGGGTATCTAATCC")

Fprimer_complement <- complement(DNAString(f_primer))
Fprimer_revComplement <- reverseComplement(DNAString(f_primer))

Rprimer_complement <- complement(DNAString(r_primer))
Rprimer_revComplement <- reverseComplement(DNAString(r_primer))

pos_control <-
  vcountPattern(pattern = "CGGAATTACTGGGCG",
                subject = all_seqs,
                fixed = FALSE)

paste(
  "Positive control is found in",
  round(sum(pos_control)/length(all_seqs) * 100, digits = 2),
  "% of sequences"
)

test_pos_control <- 
  vmatchPattern(pattern = "CGGAATTACTGGGCG", 
                subject = all_seqs, 
                fixed = FALSE)
head(test_pos_control)
pos_degen_control <-
  vcountPattern(pattern = "CCTACGGGNGGCWGCAG", 
                subject = all_seqs, 
                fixed = FALSE)

paste(
  "Positive control with degenerate bases is found in",
  round(sum(pos_degen_control) / length(all_seqs) * 100, digits = 2),
  "% of sequences"
)

```
```{r Forward Primer}
Fprimer_vmatch <- 
  vcountPattern(pattern = f_primer, 
                subject = all_seqs, 
                fixed = FALSE)

paste(
  "The forward primer is found in",
  round(sum(Fprimer_vmatch) / length(all_seqs) * 100, digits = 2),
  "% of sequences"
)

# Then double check with complement of forward primer 
Fprimer_complement_vmatch <- 
  vcountPattern(pattern = Fprimer_complement, 
                subject = all_seqs, 
                fixed = FALSE)

paste(
  "The complement of the forward primer is found in",
  round(sum(Fprimer_complement_vmatch) / length(all_seqs) * 100, digits = 2),
  "% of sequences"
)
```
```{r Reverse Primer}
Rprimer_vmatch <-
  vcountPattern(pattern = r_primer,
                subject = all_seqs,
                fixed = FALSE)

paste(
  "The reverse primer is found in",
  round(sum(Rprimer_vmatch) / length(all_seqs) * 100, digits = 2),
  "% of sequences"
)

# Then double check with complement of reverse primer
Rprimer_complement_vmatch <-
  vcountPattern(pattern = Rprimer_complement,
                subject = all_seqs,
                fixed = FALSE)

paste(
  "The complement of the reverse primer is found in",
  round(sum(Rprimer_complement_vmatch) / length(all_seqs) * 100, digits = 2),
  "% of sequences"
)
```


```{r remove extra one}
setdiff(basename(reverse_reads), gsub("_1.fastq.gz","_2.fastq.gz", basename(forward_reads)))
reverse_reads <- reverse_reads[basename(reverse_reads) != "SRR35320083_2.fastq.gz"]
length(forward_reads)
length(reverse_reads)

```

```{r pre-trimming}

sample_names <- sapply(strsplit(basename(forward_reads), "_"), `[`, 1)

head(sample_names)

filtered_fastqs_path <- "data/01_QualityTrimming/filtered_fastqs"

filtered_fastqs_path

filtered_forward_reads <-
  file.path(filtered_fastqs_path, paste0(sample_names, "_R1_filtered.fastq.gz"))

length(filtered_forward_reads)

filtered_reverse_reads <-
  file.path(filtered_fastqs_path, paste0(sample_names, "_R2_filtered.fastq.gz"))

head(filtered_reverse_reads)
```
```{r Trimming!}
filtered_reads <- 
  filterAndTrim(
    fwd = forward_reads,
    filt = filtered_forward_reads,
    rev = reverse_reads,
    filt.rev = filtered_reverse_reads,
    truncLen = c(280, 220),
    trimLeft = c(17, 21),
    maxN = 0,
    maxEE = c(1, 1),
    truncQ = 2,
    rm.phix = TRUE,
    compress = TRUE,
    multithread = 10
  )

```

```{r Plot Trimmed}
set.seed(100)
random_samples <- sample(length(filtered_forward_reads), 1)

forward_filteredQual_plot_1 <- 
  plotQualityProfile(filtered_forward_reads[random_samples]) +
  labs(title = "Trimmed Forward Read Quality")

reverse_filteredQual_plot_1 <- 
  plotQualityProfile(filtered_reverse_reads[random_samples]) +
  labs(title = "Trimmed Reverse Read Quality")

forward_filteredQual_plot_1 + reverse_filteredQual_plot_1

```

```{r plot aggregated post trimmed data}
forward_postQC_plot <- 
  plotQualityProfile(filtered_forward_reads, aggregate = TRUE) +
  labs(title = "Forward Post-QC")

reverse_postQC_plot <- 
  plotQualityProfile(filtered_reverse_reads, aggregate = TRUE) +
  labs(title = "Reverse Post-QC")

postQC_aggregate_plot <- 
  forward_postQC_plot + reverse_postQC_plot

postQC_aggregate_plot

```

```{r save file}
save(filtered_reads, file = "data/01_QualityTrimming/filtered_reads.RData")
```

```{r assess filter and trim}
install.packages("DT")


filtered_df <- as.data.frame(filtered_reads) %>%
  mutate(percent.retained = reads.out / reads.in)

DT::datatable(filtered_df)


read_stats_df <- 
  filtered_df %>%
  reframe(
    median_reads_in = median(reads.in),
    median_reads_out = median(reads.out),
    median_percent_retained = median(reads.out) / median(reads.in),
    max_percent_retained = max(reads.out / reads.in),
    min_percent_retained = min(reads.out / reads.in)
  )


read_stats_df

numSeqs_QC_dotplot <-
  filtered_df %>%
  ggplot(aes(x = reads.in, y = reads.out)) + 
  geom_point(alpha = 0.5, size = 2) + 
  labs(x = "# of Raw Seqs", 
       y = "# of Seqs Retained") + 
  geom_abline(slope = 1, intercept = 0, color = "deeppink")

numRetained_QC_histplot <- 
  filtered_df %>%
  ggplot(aes(x = reads.out)) + 
  geom_histogram() + 
  labs(x = "# of Seqs Retained", 
       y = "# of Samples")

percSeqs_QC_histplot <- 
  filtered_df %>%
  ggplot(aes(x = percent.retained)) + 
  geom_histogram() + 
  labs(x = "% of Seqs Retained", 
       y = "# of Samples") + 
  scale_x_continuous(limits = c(0, 1))

numSeqs_QC_dotplot + numRetained_QC_histplot + percSeqs_QC_histplot + 
  plot_annotation(tag_levels = "A")
```

```{r final visualization}
preQC_aggregate_plot / postQC_aggregate_plot
```

