---
title: "06_Composition.Rmd"
author: "Morrow Zhang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
# Load in the packages 
pacman::p_load(tidyverse, devtools, DT, phyloseq, patchwork, 
               install = FALSE)
source("code/colors_and_shapes.R")
```

```{r}
load("data/scaled_physeq.RData")

# Look at the data 
scaled_physeq
```

```{r}
min(sample_sums(scaled_physeq))
range(sample_sums(scaled_physeq))
```

```{r}
# Create a phylum level dataframe
phylum_df <- 
  scaled_physeq %>%
  # Agglomerate all ASV counts within a phylum
  tax_glom(taxrank = "Phylum") %>%
  # Calculate the relative abundance! 
  transform_sample_counts(function(x) {x/sum(x)}) %>%
  # Create a dataframe from phyloseq object
  psmelt()
  # Filter out Phyla < 1 % 
  #dplyr::filter(Abundance > 0.01) %>%

## What are the phylum abundances? 
phylum_df %>%
  group_by(Phylum) %>%
  summarize(mean_PercAbund = round(mean(Abundance), digits = 4)) %>%
  arrange(-mean_PercAbund) %>%
  datatable()

# Make a list of phyla the top phyla 
top10_phyla <- 
  phylum_df %>%
  group_by(Phylum) %>%
  summarize(mean_PercAbund = mean(Abundance)) %>%
  arrange(-mean_PercAbund) %>%
  head(n = 10) %>%
  pull(Phylum)

# show it
top10_phyla
```


```{r}
### Plot the Top 10 Phyla


phylum_df %>%
  dplyr::filter(Phylum %in% top10_phyla) %>%
  ggplot(aes(x = AttemptStatus, 
             y = Abundance, 
             fill = Phylum, 
             color = Phylum)) +
  facet_wrap(Phylum ~ ., scales = "free", nrow = 2) +
  
  # add jitter + boxplot
  geom_jitter(width = 0.2) +
  geom_boxplot(outlier.shape = NA, alpha = 0.5) +
  
  # use your selected colors
  scale_fill_manual(values = phylum_colors) +
  scale_color_manual(values = phylum_colors) +
  
  theme_bw() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
    axis.title.x = element_blank()
  )

ggsave(
  filename = "figures/06_Composition/Top10_Phyla_AttemptStatus.png",
  width = 12,
  height = 8,
  dpi = 300
)
```

```{r}
# Calculate the Family relative abundance 
# Note: The read depth MUST be normalized in some way: scale_reads
ASV_df <- 
  scaled_physeq %>%
  # Prune out ASVs that have fewer than ~1%! 
  ## LOOK AT HOW MANY ARE REMOVED! We scaled to 2,107 reads! 
  prune_taxa(taxa_sums(.) >= 211, .) %>%
  # agglomerate at the phylum level 
  tax_glom(taxrank = "ASV") %>% 
  # Transform counts to relative abundance 
  transform_sample_counts(function (x) {x/sum(x)}) %>%
  # Melt to a long format 
  psmelt() 


# Make a list of phyla the top 10 ASVs in the Dataset
top15_ASVs <- 
  ASV_df %>%
  group_by(ASV) %>%
  summarize(mean_PercAbund = mean(Abundance)) %>%
  arrange(-mean_PercAbund) %>%
  head(n = 15) %>%
  pull(ASV)

# show it 
top15_ASVs
```

```{r}
### Plot the Top 15 ASVs

top15_asv_plot <- ASV_df %>%
  dplyr::filter(ASV %in% top15_ASVs) %>%
  ggplot(aes(x = AttemptStatus, 
             y = Abundance, 
             fill = Phylum, 
             color = Phylum)) +
  
  facet_wrap(ASV ~ Genus, scales = "free", nrow = 3) +
  
  # add jitter + boxplot
  geom_jitter(width = 0.2) +
  geom_boxplot(outlier.shape = NA, alpha = 0.5) +
  
  # use selected colors
  scale_fill_manual(values = phylum_colors) +
  scale_color_manual(values = phylum_colors) +
  
  theme_bw() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
    axis.title.x = element_blank()
  )
top15_asv_plot
### Save the plot

ggsave(
  filename = "figures/06_Composition/Top15_ASVs_AttemptStatus.png",
  plot = top15_asv_plot,
  width = 14,
  height = 10,
  dpi = 300
)
```

```{r}
devtools::session_info()
```

